image: python:3.6
stages:
  - test

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/pip-cache"

cache:
  paths:
    - "$CI_PROJECT_DIR/pip-cache"
  key: "$CI_PROJECT_ID"

before_script:
  ## Setup SSH for cloning repos on gitlab.hydra.org.uk inside the docker/CI environment
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh

  - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts

  # Install the required utilties and pipenv
  - apt-get update -qq
  - apt-get install -y glpk-utils libgl1-mesa-glx libegl1-mesa libxrandr2 libxrandr2 libxss1 libxcursor1 libxcomposite1 libasound2 libxi6 libxtst6 wget
  - wget https://repo.anaconda.com/archive/Anaconda3-2020.02-Linux-x86_64.sh
  - bash Anaconda3-2020.02-Linux-x86_64.sh -b
  - eval "$(/root/anaconda3/bin/conda shell.bash hook)"
  - conda init
  - source /root/.bashrc
  - conda install -c conda-forge pyomo pytest-cov pypsa glpk
  - conda install -c anaconda click numpy pandas networkx pytest pytables

test:test:
  stage: test
  script:
    - python setup.py develop --with-glpk
    - pytest tests --cov=pyene
