image: python:latest
stages:
  - test

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/pip-cache"

cache:
  paths:
    - "$CI_PROJECT_DIR/pip-cache"
  key: "$CI_PROJECT_ID"

before_script:
  ## Setup SSH for cloning repos on gitlab.hydra.org.uk inside the docker/CI environment
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh

  - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts

  # Install the required utilties and pipenv
  - apt-get update -qq && apt-get install -y glpk-utils
  - pip install pyomo click numpy pandas networkx pytest pytest-cov pypsa tables

test:test:
  stage: test
  script:
    - pip install .
    - pytest tests --cov=pyene


test:run:
  stage: test
  script:
    - pip install .
    - pyene run-e
    - pyene run-n
    - pyene run-en

